### ISSUE TITLE
ProcMonX will not start under Windows 10

### ISSUE THREAD

**Issue by pc-dok** [zodiacon/ProcMonX#1]
hi procmonx chief
i download today the beta version 0.2, but it dont open on a windows 10 - 1709. is there a limitation from OS or why does the exe not open?

**Comment by zodiacon** [comment]
I don't know. I uses 1709 and it opens up just fine. It does require elevation - do you get the elevation prompt?

**Comment by pc-dok** [comment]
Yes, i get the elevation prompt, and I see it a short time in taskmanager than it will close. Can I start it maybe with a debug info ?

regards

Franco

Von: Pavel Yosifovich [mailto:notifications@github.com]
Gesendet: Donnerstag, 25. Januar 2018 13:27
An: zodiacon/ProcMonX <ProcMonX@noreply.github.com>
Cc: Franco König - N4K <info@network4kmu.at>; Author <author@noreply.github.com>
Betreff: Re: [zodiacon/ProcMonX] ProcMonX will not start under Windows 10 (#1)


I don't know. I uses 1709 and it opens up just fine. It does require elevation - do you get the elevation prompt?

**Comment by zodiacon** [comment]
There is nothing like that at the moment. I've tested in on x64 only. The best you can do is compile it from source and see what's going on. Also make sure you have .NET 4.6.x installed.

**Comment by pc-dok** [comment]
Hmm ok, i dont «compile» something in my mind, so hope there is a howto for compiling it self. I have .net framework 4.7.1 installed, is that maybe a problem?

franco

**Comment by zodiacon** [comment]
Should be ok.
I will create another release with some diagnostics so the error you get is visible.

**Comment by zodiacon** [comment]
I created another release that should show the error message when the process crashes.

**Comment by pc-dok** [comment]
Ok, now i get this failures:

Is there also a log file where I can send?

Regards franco

[cid:image001.png@01D395E7.B1E0F390]

[cid:image002.png@01D395E7.B1E0F390]

**Comment by zodiacon** [comment]
The images don't show up on Github... can you try attaching another way?

**Comment by pc-dok** [comment]
![image](https://user-images.githubusercontent.com/9332052/35390581-454a676e-01dc-11e8-9e0e-26c6e57a3800.png)

**Comment by pc-dok** [comment]
![image](https://user-images.githubusercontent.com/9332052/35390609-5d57b488-01dc-11e8-8fee-3a921237ace4.png)

**Comment by pc-dok** [comment]
so the second picture is the first one sorry

**Comment by zodiacon** [comment]
OK. Now I understand why it fails. It's because your system is non-English. Let me do some fixing

**Comment by pc-dok** [comment]
aha, ok, yes i am here from the switzerland :)

**Comment by pc-dok** [comment]
and yes i think that can be, on a azure w2k16 server, your tool is working fine

**Comment by zodiacon** [comment]
try this release: https://github.com/zodiacon/ProcMonX/releases/tag/0.21-beta

**Comment by pc-dok** [comment]
Now it opens and working fine, thank you for that asap support, now i can test it, need it for my citrix cache disk to look what is filling up my cache disk 😊
