### ISSUE TITLE
ProcMonX compile error on vs2015

### ISSUE THREAD

**Issue by Miracle-doctor** [zodiacon/ProcMonX#6]
When compiling default source code 130 errors ocurred. How to fix it?

**Comment by zodiacon** [comment]
What kind of errors are you getting?

**Comment by Miracle-doctor** [comment]
1>------ Build started: Project: ProcMonX, Configuration: Debug Any CPU ------
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\Models\Options.cs(12,39,12,41): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\Models\Options.cs(12,39,12,41): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\Models\Options.cs(14,2,14,2): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\Tracing\FilterFactory.cs(18,40,18,46): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\Tracing\FilterFactory.cs(21,38,21,44): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Filters\ProcessNamesFilterViewModel.cs(22,35,22,37): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Filters\ProcessNamesFilterViewModel.cs(22,35,22,37): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Filters\ProcessNamesFilterViewModel.cs(22,86,22,86): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\EventTypeViewModel.cs(24,17,24,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(86,39,86,43): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\EventTypeViewModel.cs(24,17,24,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(89,38,89,42): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\EventTypeViewModel.cs(26,10,26,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(93,40,93,44): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(96,41,96,45): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(99,47,99,51): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(102,50,102,54): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(105,48,105,52): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(108,53,108,57): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(111,47,111,51): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(114,46,114,50): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(117,44,117,48): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(120,44,120,48): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(123,44,123,48): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(126,37,126,41): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(129,39,129,43): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(132,41,132,45): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(136,43,136,47): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(140,38,140,42): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(144,39,144,43): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(147,42,147,46): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(150,55,150,59): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(153,39,153,43): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(156,48,156,52): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(159,51,159,55): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(162,47,162,51): error CS1003: Syntax error, ':' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(175,17,175,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(175,17,175,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(56,17,56,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(23,17,23,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(56,17,56,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(23,17,23,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(24,17,24,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(28,10,28,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(57,17,57,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(31,17,31,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(31,17,31,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(32,17,32,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(66,9,66,28): error CS1014: A get or set accessor expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(176,17,176,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(181,10,181,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(186,17,186,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(186,17,186,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(188,10,188,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(193,17,193,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(193,17,193,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(194,17,194,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(199,10,199,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(202,17,202,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(202,17,202,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(204,10,204,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(209,17,209,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(209,17,209,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(36,10,36,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(210,17,210,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(217,10,217,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(39,37,39,39): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(39,37,39,39): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterRuleViewModel.cs(39,92,39,92): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\EventsViewModel.cs(28,17,28,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\EventsViewModel.cs(28,17,28,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterDialogViewModelBase.cs(19,35,19,37): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterDialogViewModelBase.cs(19,35,19,37): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\FilterDialogViewModelBase.cs(19,90,19,90): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\EventsViewModel.cs(29,17,29,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(66,29,66,42): error CS1014: A get or set accessor expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\EventsViewModel.cs(44,10,44,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(66,43,66,43): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(94,17,94,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(94,17,94,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(95,17,95,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(99,10,99,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(102,17,102,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(102,17,102,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(103,17,103,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureFilterViewModel.cs(110,2,110,2): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureViewModel.cs(66,17,66,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureViewModel.cs(66,17,66,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureViewModel.cs(67,17,67,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\Tabs\CaptureViewModel.cs(81,10,81,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(231,50,231,54): error CS1003: Syntax error, ',' expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(294,17,294,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(294,17,294,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(296,10,296,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(345,17,345,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(345,17,345,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(346,17,346,18): error CS1002: ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\MainViewModel.cs(350,10,350,10): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(19,34,19,36): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(19,34,19,36): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(19,83,19,83): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(20,34,20,36): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(20,34,20,36): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(20,83,20,83): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(33,17,33,19): error CS1043: { or ; expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(33,17,33,19): error CS1513: } expected
1>D:\av\ProcMonX-master\ProcMonX-master\ProcMonX\ViewModels\TabItemViewModelBase.cs(35,10,35,10): error CS1513: } expected
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by zodiacon** [comment]
Are you using VS 2017?

**Comment by zodiacon** [comment]
You must use VS 2017 as some C# 7 features are in use.

**Comment by Miracle-doctor** [comment]
okey. I'll download and install it.
